name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.24.3
      ALPINE_VERSION: 3.21
      GORELEASER_VERSION: v2.9.0
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/sawmills/goreleaser-alpine
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            GO_VERSION=${{ env.GO_VERSION }}
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            GORELEASER_VERSION=${{ env.GORELEASER_VERSION }}
          tags: |
            ghcr.io/sawmills/goreleaser-alpine:go${{ env.GO_VERSION }}-goreleaser${{ env.GORELEASER_VERSION }}-alpine${{ env.ALPINE_VERSION }}
            ghcr.io/sawmills/goreleaser-alpine:latest
            ghcr.io/sawmills/goreleaser-alpine:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
